version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        restart: always
        command:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--storage.tsdb.retention=1d"
        - "--web.enable-lifecycle"
        volumes:
          - ./prometheus/:/etc/prometheus/
          - prometheus_data:/prometheus
        ports:
          - "9090:9090"

    alertmanager:
        image: prom/alertmanager
        ports:
          - 9093:9093
        volumes:
          - ./alertmanager/:/etc/alertmanager/
        restart: always
        #command:
        #  - '--config.file=/etc/alertmanager/config.yml'
        #  - '--storage.path=/alertmanager'

    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        ports:
          - "3000:3000"
        depends_on:
          - prometheus
        volumes:
          - grafana_data:/var/lib/grafana
          - ./grafana/provisioning/:/etc/grafana/provisioning/

    cadvisor:
        image: google/cadvisor
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
        ports:
          - 18080:8080
        restart: always