version: "3"
services:
  config-server-node1:
    image: akjamie/cloud-config-service:1.0.0
    environment:
      CONFIG_REPOSITORY_URL: https://github.com/cloud-poc/devops-config-service-repo
      EUREKA_CLIENT_SERVICE_URL: http://service-registry-node1:8761/eureka
    ports:
      - 8888:8888
  
  config-server-node2:
    image: akjamie/cloud-config-service:1.0.0
    environment:
      CONFIG_REPOSITORY_URL: https://github.com/cloud-poc/devops-config-service-repo
      EUREKA_CLIENT_SERVICE_URL: http://service-registry-node1:8761/eureka
    ports:
      - 8889:8888
    