version: "3"
services:
  # service registry cluster - node1
  service-registry-1:
    image: akjamie/cloud-service-registry:1.0.0
    container_name: service-registry-node1
    environment:
      - EUREKA_INSTANCE_HOSTNAME=service-registry-node1
      - EURAKE_CLIENT_SERVICE_URL=http://service-registry-node2:8761/eureka
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
    ports:
      - 8761:8761
  
  # service registry cluster - node2
  service-registry-2:
    image: akjamie/cloud-service-registry:1.0.0
    container_name: service-registry-node2
    environment:
      - EUREKA_INSTANCE_HOSTNAME=service-registry-node2
      - EURAKE_CLIENT_SERVICE_URL=http://service-registry-node1:8761/eureka
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
    ports:
      - 8762:8761
    