spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: SpringBootHikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/catalog?useSSL=false&charset=utf8
    jdbcUrl: jdbc:mysql://192.168.99.100:3306/catalog?useSSL=false&charset=utf8
    username: jamie
    password: Hsbc1234
    initialization-mode: always
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      idle-timeout: 30000
      minimum-idle: 2
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
eureka.client.service-url:
  defaultZone: http://192.168.99.100:9000/eureka/
spring.cloud.discovery.client:
  health-indicator:
    enabled: true
    include-description: true
spring.zipkin.base-url: http://192.168.99.100:9411/
spring.sleuth.sampler.probability: 1

spring.rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest