# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout:      10s # is set to the global default (10s).

# Alertmanager configuration

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'authorization-service'
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: ['192.168.65.2:8044']
    
  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: ['192.168.65.2:8080']
    
  - job_name: 'catalog-service'
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: ['192.168.65.2:9001']

  - job_name: 'inventory-service'
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: ['192.168.65.2:9002']

  - job_name: 'registry-service'
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: ['service-registry-node2:8761','service-registry-node1:8761']

  - job_name: 'config-service'
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: ['config-server-node2:8888','config-server-node1:8888']

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']