zuul:
  prefix: /
  retryable: true
  sensitive-headers: Authorization, Cookie, Set-Cookie
  ignored-services: '*'
  routes:
    catalogservice:
      path: /catalog/**
      serviceId: catalog-service
    inventoryservice:
      path: /inventory/**
      serviceId: inventory-service
    authorizationservice:
      path: /uua/**
      serviceId: authorization-service

hystrix:
  command:
    default:
      execution.isolation:
        semaphore.maxConcurrentRequests: 50
        thread:
          timeoutInMilliseconds: 30000


health-check.enabled: true
spring.sleuth.sampler.probability: 1.0
eureka.client.service-url:
  defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}

zuul.filter:
  authFilter:
    enabled: true
    headers: Authorization
    
security:
  oauth2:
    resource:
      token-info-uri: ${SECURITY_OAUTH2_TOKEN_INFO_URL:http://localhost:8044/uaa/oauth/check_token}
      verifier-key.file-path: ${SECURITY_OAUTH2_VERIFIER_KEY_PATH:publicKey.pem}
    client:
      client-id: ${SECURITY_OAUTH2_CLIENT_ID:client_2}
      client-secret: ${SECURITY_OAUTH2_CLIENT_SECRET:123456}