zuul:
  prefix: /proxy
  retryable: true
  sensitive-headers: X-XHR-User-ID
  ignored-services: '*'
  routes:
    catalogservice:
      path: /catalog/**
      serviceId: catalog-service
    inventoryservice:
      path: /inventory/**
      serviceId: inventory-service

health-check.enabled: true
spring.zipkin.base-url: http://zipkin:9411/
spring.sleuth.sampler.probability: 1
eureka.client.service-url:
  defaultZone: ${EURAKE_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}