zuul:
  prefix: /proxy
  retryable: true
  sensitive-headers: Authorization
  ignored-services: '*'
  routes:
    catalogservice:
      path: /catalog/**
      serviceId: catalog-service
    inventoryservice:
      path: /inventory/**
      serviceId: inventory-service
    authorizationservice:
      path: /uua/**
      serviceId: authorization-service

health-check.enabled: true
spring.sleuth.sampler.probability: 1
