zuul:
  prefix: /
  retryable: true
  sensitive-headers: Authorization, Cookie, Set-Cookie
  ignored-services: '*'
  routes:
    catalogservice:
      path: /catalog/**
      serviceId: catalog-service
    inventoryservice:
      path: /inventory/**
      serviceId: inventory-service
    authorizationservice:
      path: /uua/**
      serviceId: authorization-service

health-check.enabled: true
spring.sleuth.sampler.probability: 1
eureka.client.service-url:
  defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}

zuul.filter:
  authFilter:
    enabled: true
    headers: Authorization