spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: SpringBootHikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?allowPublicKeyRetrieval=true&useSSL=false&charset=utf8
    username: jamie
    password: Hsbc1234
    initialization-mode: always
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      idle-timeout: 30000
      minimum-idle: 2
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sleuth.sampler.probability: 1.0
    
security.oauth2.jwt.key-pair:
  store-pass: ${JWT_KEYPAIR_STOREPASS:Test1234}
  alias: ${JWT_KEYPAIR_ALIAS:internal-certs}
  file-path: ${JWT_KEYPAIR_PATH:keystore.p12}

swagger.api:
  enabled: true
  title: "Authorization Service"
  description: "Custom oauth2 based authorization service for microservice"
  terms-of-service-url: "https://oauth.net/2"
  version: "v1.0.0"
  controller:
    base-package: "org.akj"
  contact:
    name: "Jamie Zhang"
    email: "akjamie.zhang@outlook.com"