spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: SpringBootHikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catalog?allowPublicKeyRetrieval=true&useSSL=false&charset=utf8
    jdbcUrl: jdbc:mysql://localhost:3306/catalog?allowPublicKeyRetrieval=true&useSSL=false&charset=utf8
    username: jamie
    password: Hsbc1234
    initialization-mode: always
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      idle-timeout: 30000
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sleuth.sampler.probability: 1

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:8080/uaa/oauth/token_key
      token-info-uri: /uaa/oauth/check_token
